### PR TITLE
Replace use of StateController by calls to KiteAPI instead

### PR DESCRIPTION
**Pull request by abe33**

### CODE REVIEW

**Comment by jansorg** [comment]
@abe33 This is what I noticed on Windows 10. I'm not sure if these issues are new in this branch.

- Status panel takes 5 to 10s to appear when Kite isn't running: Stop kite, click the status panel. The panel needs a few seconds to appear.

- Status panel not workign after Kite was starte: Click "Launch Kite" in the panel above. Close the panel after Kite was started in the background. Clicking on the status bar icon to show the panel does nothing.

- Clicking "Install now" opens the web browser to download the setup file. I think that this was different in the old version. Kite wasn't installed after the download finished.

**Comment by abe33** [comment]
1. I think it was always like that, the code making the check haven't changed in the slightest, it was just moved in a different object.
2. I don't reproduce, what errors do you see in the console?
3. No it was a change requested a few weeks back, it's the same currently on master

**Comment by jansorg** [comment]
@abe33 
Thanks for the feedback!
1. Okay for now. I'll create a new issue for this
2. I was able to reproduce on Windows 10, there are no new errors in the console
3. Okay, thanks

**Comment by jansorg** [comment]
@abe33 Test on Windows 10:
- quit kite
- click the kite icon to open the panel
- click "Launch Kite" and close the panel
- wait a moment and click the Kite again again
- the status panel won't open again, I don't se errors in the console. See the screenshot which was recorded right after I clicked the icon for the last time
image

**Comment by jansorg** [comment]
@abe33 Testing on macOS:
Same thing with the status panel as on Windows.

I've noticed this in the dev console:
bildschirmfoto 2018-07-20 um 16 02 10

**Comment by jansorg** [comment]
@abe33 Thanks for the update!
Now I'm unable to close the panel after clicking on "Launch Kite". It's always showing "Launching Kite" even  when Kite is back online and the Kite icon switched back to blue in Atom.

screenshot_20180723_165048

**Pull request merged**
