### PR TITLE
Remove legacy sidebar implementation in favor of the dock API

### PR DESCRIPTION
**Pull request by abe33**
This PR basically remove the setting and use the dock API version wherever we were switching behavior based on that setting. Also, the sidebars no longer have a close button nor a resizer as we're letting the dock handles that for us.

### CODE REVIEW

**Comment by jansorg** [comment]
@abe33 I noticed that the plugin's sidebar is no longer adjusting when resized.
screenshot_20180314_175643

**Comment by jansorg** [comment]
Clicking the X in the upper right corner is not closing the panel.

**Comment by dbratz1177** [comment]
I'm also seeing the behavior @jansorg sees

**Comment by abe33** [comment]
Yeah sorry forgot to remove the close button and fixed width part, fixed now

**Comment by mwichary** [comment]
👍

**Pull request merged**
