### PR TITLE
Change search endpoint

### PR DESCRIPTION
**Pull request by abe33**
Ref #303

### CODE REVIEW

**Comment by jlozano** [comment]
@abe33 I see the search requests coming in on the backend, but i do not get any results in atom?

**Comment by jlozano** [comment]
@abe33 as far as I can tell the response looks correct. E.G for `GET localhost:46624/api/editor/search?limit=10&offset=0&q=js` I get the following results:
```
{
    "language": "python",
    "total": 9,
    "start": 0,
    "end": 9,
    "results": [
        {
            "type": "value",
            "result": {
                "id": "python;json",
                "kind": "module",
                "repr": "json",
                "type": "module",
                "type_id": ""
            }
        },
        {
            "type": "value",
            "result": {
                "id": "python;json.dumps",
                "kind": "function",
                "repr": "json.dumps",
                "type": "function",
                "type_id": ""
            }
        },
        {
            "type": "value",
            "result": {
                "id": "python;json.loads",
                "kind": "function",
                "repr": "json.loads",
                "type": "function",
                "type_id": ""
            }
        },
        {
            "type": "value",
            "result": {
                "id": "python;json.load",
                "kind": "function",
                "repr": "json.load",
                "type": "function",
                "type_id": ""
            }
        },
        {
            "type": "value",
            "result": {
                "id": "python;json.dump",
                "kind": "function",
                "repr": "json.dump",
                "type": "function",
                "type_id": ""
            }
        },
        {
            "type": "value",
            "result": {
                "id": "python;jsonschema",
                "kind": "module",
                "repr": "jsonschema",
                "type": "module",
                "type_id": ""
            }
        },
        {
            "type": "value",
            "result": {
                "id": "python;jsonfield",
                "kind": "module",
                "repr": "jsonfield",
                "type": "module",
                "type_id": ""
            }
        },
        {
            "type": "value",
            "result": {
                "id": "python;jsonfield.fields.JSONField",
                "kind": "type",
                "repr": "jsonfield.fields.JSONField",
                "type": "SubfieldBase",
                "type_id": "python;jsonfield.subclassing.SubfieldBase"
            }
        },
        {
            "type": "value",
            "result": {
                "id": "python;jsonpickle",
                "kind": "module",
                "repr": "jsonpickle",
                "type": "module",
                "type_id": ""
            }
        }
    ]
}
```

**Comment by abe33** [comment]
Wow, my bad, I thought it was just an url change, but the whole JSON have changed. We no longer have a `python_results` object and we're no longer presenting local results right?

**Comment by jlozano** [comment]
@abe33 correct we no longer have a `python_results` object. What do you mean by "local results"? Local code results?

**Comment by abe33** [comment]
Yes exactly, maybe I've missed something but I didn't saw any to know whether a result is from the local code or not.

**Comment by jansorg** [comment]
@jlozano mentioned on Slack that he would like to test this...

**Comment by jlozano** [comment]
@abe33 the search aspect looks good to me, however it looks like it is using `/api/editor/value` to fetch the data instead of `/api/editor/symbol` ?

**Comment by jlozano** [comment]
@abe33 we can deal with not using the `/api/editor/value` endpoint in another PR, this looks good to me, feel free to merge!

**Pull request merged**
