### PR TITLE
Tweak tour

### PR DESCRIPTION
**Pull request by abe33**

### CODE REVIEW

**Comment by jlozano** [comment]
@abe33 looking good! One minor thing, can we move the `To manage Kite's permissions, click here` and `For more help topics, go to help.kite.com` to be not part of the scrollable region? I know this will make the scrollable region slightly smaller but I think these are important to show to the user. Sorry I should have clarified this in the original comment.

**Comment by jlozano** [comment]
Ref: https://github.com/kiteco/atom-plugin/issues/196

**Comment by abmirayo** [comment]
@abe33 It looks awesome, I noticed 2 things in the gif screenshot in #196:

- At the top, the Kite logo is slightly vertically misaligned, it should be more centered with the "Kite for Python is installed and ready!", and with a bit more margin between the logo and the text.

- The text of the features seems center aligned in the screenshot; it should be left aligned, like the titles.

**Comment by abmirayo** [comment]
@abe33 👌  looks gorg

**Pull request merged**
